db:
     image: mysql
     ports:
         - "3306:3306"
     volumes:
         - mysql:/var/lib/mysql


web:
    image: apachephp5
    environment:
         - VIRTUAL_HOST=local.abacate.com.br
    ports:
         - "80:80"
    volumes:
         - app/:/var/www/html/
    links:
         - db


